// <auto-generated />
namespace SistemaRiesgo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class agregadaClaseEmpleadoyllavesforaneasenEmpres : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agregadaClaseEmpleadoyllavesforaneasenEmpres));
        
        string IMigrationMetadata.Id
        {
            get { return "201710282252068_agregada Clase Empleado y llaves foraneas en Empres"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
