// <auto-generated />
namespace SistemaRiesgo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TextAreaparaObjetivosyAlcanceagregadosenmodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TextAreaparaObjetivosyAlcanceagregadosenmodels));
        
        string IMigrationMetadata.Id
        {
            get { return "201710282257316_TextArea para Objetivos y Alcance agregados en models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
