<%@ Page Title="Departamentos" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ListaDepartamentos.aspx.cs" Inherits="SistemaRiesgo.ListaDepartamentos" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <section>
        <div>
            <h2><%: Page.Title %></h2>
            <asp:Label ID="accion" Text="" runat="server" CssClass="text-info"/>
            <asp:ValidationSummary ShowModelStateErrors="true" runat="server" CssClass="text-danger" />
            <asp:GridView ID="listaDepartamentos" runat="server" 
                ItemType="SistemaRiesgo.Models.Departamento" DataKeyNames="codigo"
                SelectMethod="getDepartamentos"
                DeleteMethod="listaDepartamentos_DeleteItem"
                UpdateMethod="listaDepartamentos_UpdateItem"
                AutoGenerateDeleteButton="true" AutoGenerateEditButton="true"
                AutoGenerateSelectButton="true"
                AutoGenerateColumns="false"
                CssClass ="table table-striped table-hover"
                BorderStyle ="Solid"
                BorderColor="WhiteSmoke"
                >
                <EmptyDataTemplate>
                    <br />
                    <br />
                    <table >
                        <tr>
                            <td >
                                No hay Departamentos registrados aun.
                            </td>
                        </tr>
                    </table>
                </EmptyDataTemplate>
                <Columns>
                    <asp:DynamicField ControlStyle-BorderColor="Black" DataField="nombre" />
                    <asp:TemplateField HeaderText="Activos" >
                        <ItemTemplate>
                            <asp:Label ID="activos" runat="server">0</asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
                
            </asp:GridView>
        </div>
        <div>
            <a runat="server" visible ="true" id="empleados" href="~/Admin/ListaEmpleados">Ver Empleados</a>
        </div>
    </section>
    <asp:Label ID="mensaje" runat="server"></asp:Label>
    <br />
    <br />
    <asp:HyperLink ID="btnNuevo" NavigateUrl="CrearDepartamento" Text="Nuevo Departamento" runat="server" CssClass="btn btn-primary btn-sm" />
</asp:Content>
