<%@ Page Title="Departamentos" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ListaDepartamentos.aspx.cs" Inherits="SistemaRiesgo.ListaDepartamentos" MaintainScrollPositionOnPostback="true" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <section>
        <div>
            <h2><%: Page.Title %></h2>
            <asp:Label ID="accion" Text="" runat="server" CssClass="text-info"/>
            <asp:ValidationSummary ShowModelStateErrors="true" runat="server" CssClass="text-danger" />
           
             <asp:HyperLink ID="btnNuevo" NavigateUrl="CrearDepartamento" Text="Nuevo Departamento" runat="server" CssClass="btn btn-primary btn-sm" />
                
                        
            <asp:GridView ID="listaDepartamentos" runat="server" 
                ItemType="SistemaRiesgo.Models.Departamento" DataKeyNames="codigo"
                SelectMethod="getDepartamentos"
                DeleteMethod="listaDepartamentos_DeleteItem"
                UpdateMethod="listaDepartamentos_UpdateItem"
                
                onselectedindexchanged="listaDepartamentos_SelectedIndexChanged"
                AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" autogenerateselectbutton="true"
                
               
      
                



                AutoGenerateColumns="false"
                CssClass ="table table-striped table-hover"
                BorderStyle ="Solid"
                BorderColor="WhiteSmoke"
                >
                <EmptyDataTemplate>
                    <br />
                    <br />
                    <table >
                        <tr>
                            <td >
                                No hay Departamentos registrados aun.
                            </td>
                        </tr>
                    </table>
                </EmptyDataTemplate>
                <Columns>

                    
                    
                    <asp:BoundField DataField="codigo"  ItemStyle-CssClass="hiddencol" HeaderStyle-CssClass="hiddencol " />


                    
                    <asp:BoundField
                        DataField="nombre" InsertVisible="True" />

                    
                    <asp:TemplateField HeaderText="Activos" >
                        <ItemTemplate>
                            <asp:Label ID="activos" runat="server">0</asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
                
            </asp:GridView>

            <asp:Label ID="codigo"
                ForeColor="Red"
                runat="server" CssClass="hiddentext"  />

        <asp:Button Text="Ver Empleados" CssClass="btn btn-primary btn-sm" runat="server" ID="btnEnviar" OnClick="btnEnviar_Click" />
            <br />
            <br />
        




        
            <h2>Empleados Globales</h2>
            
            <asp:HyperLink ID="nuevoEmpleado" NavigateUrl="CrearEmpleadoG" Text="Crear Empleado Global" runat="server" CssClass="btn btn-primary btn-sm" />
                  
        <asp:GridView ID="listaEmpleadosG" runat="server" 
                ItemType="SistemaRiesgo.Models.Empleado" DataKeyNames="codigo"
                SelectMethod="getEmpleadosG"
                DeleteMethod="listaEmpleadosG_DeleteItem"
                UpdateMethod="listaEmpleadosG_UpdateItem"
                onselectedindexchanged="listaEmpleadosG_SelectedIndexChanged"

            AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" autogenerateselectbutton="true"
                AutoGenerateColumns="false"
                CssClass ="table table-striped table-hover"
                BorderStyle ="Solid"
                BorderColor="WhiteSmoke"
                RowHeaderColumn="listaEmpleadosG.HeaderRow.Cells[2].Visible=false;">
                <EmptyDataTemplate>
                    <br />
                    <br />
                    <table >
                        <tr>
                            <td >
                                No hay Empleados registrados aun.
                            </td>
                        </tr>
                    </table>
                </EmptyDataTemplate>
                <Columns>

                    
                    
                    <asp:BoundField DataField="codigo" ItemStyle-CssClass="hiddencol " HeaderStyle-CssClass="hiddencol " />


                    
                    <asp:BoundField DataField="nombre" InsertVisible="True" />

                    
                    
                </Columns>

            
                
            </asp:GridView>
       
            <asp:Label ID="idEG"
                ForeColor="Red"
                runat="server" CssClass="hiddentext"/>
        <asp:Button Text="Editar Permisos" CssClass="btn btn-primary btn-sm" runat="server" ID="btnEnviarid" OnClick="btnEnviarId_Click" />
        
        
        </div>
        
    </section>
    <asp:Label ID="mensaje" runat="server"></asp:Label>
    <br />
    <br />
    </asp:Content>
